name: Integration Suite

on:
  pull_request:
    branches:
    - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      with:
          # record: true
        # env:
          # overwrite commit message sent to Dashboard
          # COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          # re-enable PR comment bot
          # COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
        spec: cypress/e2e/integration/*.cy.js
        build: npm run build
        start: npm start
        wait-on: 'http://localhost:4200'